# Generated by Django 3.2.9 on 2021-11-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.CharField(max_length=8)),
                ('p_cout', models.IntegerField()),
            ],
        ),
    ]
